#!/bin/bash
set -e
# --- sqli_credential_leak ---
export DEBIAN_FRONTEND=noninteractive

# Install runtime
apt-get update -qq
apt-get install -y apache2 php libapache2-mod-php php-mysql php-sqlite3

mkdir -p /var/www/html
# Write index.php
echo 'PD9waHAKLy8gRGF0YWJhc2Ugc2V0dXAgdXNpbmcgU1FMaXRlIHZpYSBQRE8KZGVmaW5lKCdEQl9QQVRIJywgJy92YXIvZGIvYXBwLmRiJyk7CgpmdW5jdGlvbiBnZXRfZGIoKSB7CiAgICAkZGIgPSBuZXcgUERPKCdzcWxpdGU6JyAuIERCX1BBVEgpOwogICAgJGRiLT5zZXRBdHRyaWJ1dGUoUERPOjpBVFRSX0VSUk1PREUsIFBETzo6RVJSTU9ERV9TSUxFTlQpOwogICAgcmV0dXJuICRkYjsKfQoKZnVuY3Rpb24gaW5pdF9kYigpIHsKICAgICRkYiA9IGdldF9kYigpOwogICAgJGRiLT5leGVjKCJDUkVBVEUgVEFCTEUgSUYgTk9UIEVYSVNUUyBwcm9kdWN0cyAoCiAgICAgICAgaWQgSU5URUdFUiBQUklNQVJZIEtFWSBBVVRPSU5DUkVNRU5ULAogICAgICAgIG5hbWUgVkFSQ0hBUigxMjgpLAogICAgICAgIGRlc2NyaXB0aW9uIFZBUkNIQVIoMjU2KQogICAgKSIpOwogICAgJGRiLT5leGVjKCJDUkVBVEUgVEFCTEUgSUYgTk9UIEVYSVNUUyB1c2VycyAoCiAgICAgICAgaWQgSU5URUdFUiBQUklNQVJZIEtFWSBBVVRPSU5DUkVNRU5ULAogICAgICAgIHVzZXJuYW1lIFZBUkNIQVIoNjQpLAogICAgICAgIHBhc3N3b3JkIFZBUkNIQVIoMTI4KSwKICAgICAgICByb2xlIFZBUkNIQVIoMzIpCiAgICApIik7CiAgICAvLyBTZWVkIHByb2R1Y3RzIGlmIGVtcHR5CiAgICAkY291bnQgPSAkZGItPnF1ZXJ5KCJTRUxFQ1QgQ09VTlQoKikgRlJPTSBwcm9kdWN0cyIpLT5mZXRjaENvbHVtbigpOwogICAgaWYgKCRjb3VudCA9PSAwKSB7CiAgICAgICAgJGRiLT5leGVjKCJJTlNFUlQgSU5UTyBwcm9kdWN0cyAobmFtZSwgZGVzY3JpcHRpb24pIFZBTFVFUwogICAgICAgICAgICAoJ1dpZGdldCBBJywgJ0Egc3RhbmRhcmQgd2lkZ2V0IGZvciBldmVyeWRheSB1c2UnKSwKICAgICAgICAgICAgKCdXaWRnZXQgQicsICdBbiBpbXByb3ZlZCB3aWRnZXQgd2l0aCBleHRyYSBmZWF0dXJlcycpLAogICAgICAgICAgICAoJ0dhZGdldCBQcm8nLCAnUHJvZmVzc2lvbmFsIGdyYWRlIGdhZGdldCcpLAogICAgICAgICAgICAoJ0dhZGdldCBMaXRlJywgJ0xpZ2h0d2VpZ2h0IHZlcnNpb24gb2YgdGhlIGdhZGdldCcpIik7CiAgICB9CiAgICAvLyBTZWVkIHVzZXJzIGlmIGVtcHR5CiAgICAkY291bnQgPSAkZGItPnF1ZXJ5KCJTRUxFQ1QgQ09VTlQoKikgRlJPTSB1c2VycyIpLT5mZXRjaENvbHVtbigpOwogICAgaWYgKCRjb3VudCA9PSAwKSB7CiAgICAgICAgJGRiLT5leGVjKCJJTlNFUlQgSU5UTyB1c2VycyAodXNlcm5hbWUsIHBhc3N3b3JkLCByb2xlKSBWQUxVRVMKICAgICAgICAgICAgKCdzeXNhZG1pbicsICdTdXAzclMzY3IzdFNTSCEnLCAnYWRtaW4nKSwKICAgICAgICAgICAgKCdkZXBsb3knLCAnZGVwbG95X3Bhc3NfMjAyNCcsICd1c2VyJykiKTsKICAgIH0KfQoKaW5pdF9kYigpOwoKJHJlc3VsdHMgPSBbXTsKJGVycm9yID0gJyc7CiRzZWFyY2hlZCA9IGZhbHNlOwoKaWYgKGlzc2V0KCRfR0VUWydzZWFyY2gnXSkpIHsKICAgICRzZWFyY2hlZCA9IHRydWU7CiAgICAkc2VhcmNoID0gJF9HRVRbJ3NlYXJjaCddOwogICAgJGRiID0gZ2V0X2RiKCk7CiAgICAvLyBWVUxORVJBQkxFOiBkaXJlY3Qgc3RyaW5nIGNvbmNhdGVuYXRpb24sIG5vIHNhbml0aXphdGlvbgogICAgJHF1ZXJ5ID0gIlNFTEVDVCBuYW1lLCBkZXNjcmlwdGlvbiBGUk9NIHByb2R1Y3RzIFdIRVJFIG5hbWUgTElLRSAnJSIgLiAkc2VhcmNoIC4gIiUnIjsKICAgICRzdG10ID0gJGRiLT5xdWVyeSgkcXVlcnkpOwogICAgaWYgKCRzdG10ICE9PSBmYWxzZSkgewogICAgICAgICRyZXN1bHRzID0gJHN0bXQtPmZldGNoQWxsKFBETzo6RkVUQ0hfTlVNKTsKICAgIH0gZWxzZSB7CiAgICAgICAgJGluZm8gPSAkZGItPmVycm9ySW5mbygpOwogICAgICAgICRlcnJvciA9IGlzc2V0KCRpbmZvWzJdKSA/ICRpbmZvWzJdIDogJ1F1ZXJ5IGVycm9yJzsKICAgIH0KfQo/Pgo8IURPQ1RZUEUgaHRtbD4KPGh0bWwgbGFuZz0iZW4iPgo8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9IlVURi04Ij4KICAgIDx0aXRsZT5Qcm9kdWN0IENhdGFsb2c8L3RpdGxlPgogICAgPHN0eWxlPgogICAgICAgIGJvZHkgeyBmb250LWZhbWlseTogQXJpYWwsIHNhbnMtc2VyaWY7IG1hcmdpbjogNDBweDsgYmFja2dyb3VuZDogI2Y0ZjRmNDsgfQogICAgICAgIGgxIHsgY29sb3I6ICMzMzM7IH0KICAgICAgICBmb3JtIHsgbWFyZ2luLWJvdHRvbTogMjBweDsgfQogICAgICAgIGlucHV0W3R5cGU9dGV4dF0geyBwYWRkaW5nOiA2cHg7IHdpZHRoOiAzMDBweDsgZm9udC1zaXplOiAxNHB4OyB9CiAgICAgICAgaW5wdXRbdHlwZT1zdWJtaXRdIHsgcGFkZGluZzogNnB4IDE2cHg7IGZvbnQtc2l6ZTogMTRweDsgY3Vyc29yOiBwb2ludGVyOyB9CiAgICAgICAgdGFibGUgeyBib3JkZXItY29sbGFwc2U6IGNvbGxhcHNlOyB3aWR0aDogMTAwJTsgYmFja2dyb3VuZDogI2ZmZjsgfQogICAgICAgIHRoIHsgYmFja2dyb3VuZDogIzMzMzsgY29sb3I6ICNmZmY7IHBhZGRpbmc6IDEwcHg7IHRleHQtYWxpZ246IGxlZnQ7IH0KICAgICAgICB0ZCB7IGJvcmRlcjogMXB4IHNvbGlkICNjY2M7IHBhZGRpbmc6IDhweDsgfQogICAgICAgIHRyOm50aC1jaGlsZChldmVuKSB7IGJhY2tncm91bmQ6ICNmOWY5Zjk7IH0KICAgICAgICAuZXJyb3IgeyBjb2xvcjogcmVkOyB9CiAgICAgICAgLm5vLXJlc3VsdHMgeyBjb2xvcjogIzY2NjsgZm9udC1zdHlsZTogaXRhbGljOyB9CiAgICA8L3N0eWxlPgo8L2hlYWQ+Cjxib2R5PgogICAgPGgxPlByb2R1Y3QgQ2F0YWxvZzwvaDE+CiAgICA8Zm9ybSBtZXRob2Q9IkdFVCIgYWN0aW9uPSIvaW5kZXgucGhwIj4KICAgICAgICA8aW5wdXQgdHlwZT0idGV4dCIgbmFtZT0ic2VhcmNoIiBwbGFjZWhvbGRlcj0iU2VhcmNoIHByb2R1Y3RzLi4uIiB2YWx1ZT0iPD9waHAgZWNobyBpc3NldCgkX0dFVFsnc2VhcmNoJ10pID8gaHRtbHNwZWNpYWxjaGFycygkX0dFVFsnc2VhcmNoJ10sIEVOVF9RVU9URVMpIDogJyc7ID8+Ij4KICAgICAgICA8aW5wdXQgdHlwZT0ic3VibWl0IiB2YWx1ZT0iU2VhcmNoIj4KICAgIDwvZm9ybT4KCiAgICA8P3BocCBpZiAoJGVycm9yKTogPz4KICAgICAgICA8cCBjbGFzcz0iZXJyb3IiPkVycm9yOiA8P3BocCBlY2hvIGh0bWxzcGVjaWFsY2hhcnMoJGVycm9yKTsgPz48L3A+CiAgICA8P3BocCBlbmRpZjsgPz4KCiAgICA8P3BocCBpZiAoJHNlYXJjaGVkKTogPz4KICAgICAgICA8dGFibGU+CiAgICAgICAgICAgIDx0aGVhZD4KICAgICAgICAgICAgICAgIDx0cj4KICAgICAgICAgICAgICAgICAgICA8dGg+UHJvZHVjdCBOYW1lPC90aD4KICAgICAgICAgICAgICAgICAgICA8dGg+RGVzY3JpcHRpb248L3RoPgogICAgICAgICAgICAgICAgPC90cj4KICAgICAgICAgICAgPC90aGVhZD4KICAgICAgICAgICAgPHRib2R5PgogICAgICAgICAgICAgICAgPD9waHAgaWYgKGNvdW50KCRyZXN1bHRzKSA+IDApOiA/PgogICAgICAgICAgICAgICAgICAgIDw/cGhwIGZvcmVhY2ggKCRyZXN1bHRzIGFzICRyb3cpOiA/PgogICAgICAgICAgICAgICAgICAgICAgICA8dHI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGQ+PD9waHAgZWNobyAkcm93WzBdOyA/PjwvdGQ+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGQ+PD9waHAgZWNobyAkcm93WzFdOyA/PjwvdGQ+CiAgICAgICAgICAgICAgICAgICAgICAgIDwvdHI+CiAgICAgICAgICAgICAgICAgICAgPD9waHAgZW5kZm9yZWFjaDsgPz4KICAgICAgICAgICAgICAgIDw/cGhwIGVsc2U6ID8+CiAgICAgICAgICAgICAgICAgICAgPHRyPjx0ZCBjb2xzcGFuPSIyIiBjbGFzcz0ibm8tcmVzdWx0cyI+Tm8gcHJvZHVjdHMgZm91bmQuPC90ZD48L3RyPgogICAgICAgICAgICAgICAgPD9waHAgZW5kaWY7ID8+CiAgICAgICAgICAgIDwvdGJvZHk+CiAgICAgICAgPC90YWJsZT4KICAgIDw/cGhwIGVsc2U6ID8+CiAgICAgICAgPHA+RW50ZXIgYSBzZWFyY2ggdGVybSBhYm92ZSB0byBmaW5kIHByb2R1Y3RzLjwvcD4KICAgIDw/cGhwIGVuZGlmOyA/Pgo8L2JvZHk+CjwvaHRtbD4K' | base64 -d > /var/www/html/index.php

# Ensure www-data writable dirs
mkdir -p /var/db && chown www-data:www-data /var/db
mkdir -p /var/www/html/uploads && chown www-data:www-data /var/www/html/uploads

# Start application
cd /var/www/html
nohup service apache2 start > /var/log/webapp.log 2>&1 &
sleep 3

# Healthcheck
curl -sf http://localhost/app.php || curl -sf http://localhost/ && echo 'deploy_ok' || echo 'deploy_failed'

# --- ssh_login_leaked_creds ---

# Install OpenSSH server
apt-get update -y
apt-get install -y openssh-server

# Ensure SSH runtime directory exists
mkdir -p /var/run/sshd

# Configure sshd to allow password authentication and disable root login
# Remove any existing conflicting lines and set desired values
sed -i '/^#\?PasswordAuthentication/d' /etc/ssh/sshd_config
sed -i '/^#\?PermitRootLogin/d' /etc/ssh/sshd_config
echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
echo 'PermitRootLogin no' >> /etc/ssh/sshd_config

# Create low-privilege user sysadmin if not already present
id sysadmin &>/dev/null || useradd -m -s /bin/bash sysadmin

# Set password exactly as leaked via SQL injection
echo 'sysadmin:Sup3rS3cr3tSSH!' | chpasswd

# Generate SSH host keys if not already present
ssh-keygen -A

# Start SSH service
service ssh start || /usr/sbin/sshd || true

echo 'SSH setup complete. User sysadmin created with password Sup3rS3cr3tSSH!'

# --- sudo_privesc_root ---

# Install findutils to ensure /usr/bin/find is available
apt-get update -y
apt-get install -y findutils

# Create user 'sysadmin' with password 'sysadmin123' (skip if already exists)
id -u sysadmin &>/dev/null || useradd -m -s /bin/bash sysadmin
echo 'sysadmin:sysadmin123' | chpasswd

# Write the sudoers drop-in file granting NOPASSWD access to /usr/bin/find
echo 'sysadmin ALL=(root) NOPASSWD: /usr/bin/find' > /etc/sudoers.d/sysadmin
chmod 440 /etc/sudoers.d/sysadmin

# Verify sudoers syntax is valid
visudo -c -f /etc/sudoers.d/sysadmin || true

echo 'Setup complete. User sysadmin can escalate via: sudo find /. -maxdepth 0 -exec /bin/bash -p \; -quit'
