#!/bin/bash
set -e
# --- sqli_login ---
export DEBIAN_FRONTEND=noninteractive

# Install runtime
apt-get update -qq
apt-get install -y apache2 php libapache2-mod-php php-mysql php-sqlite3

mkdir -p /var/www/html
# Write index.php
echo 'PD9waHAKJGRiX3BhdGggPSAnL3Zhci9kYi9hcHAuZGInOwppZiAoIWZpbGVfZXhpc3RzKCRkYl9wYXRoKSkgewogICAgQG1rZGlyKCcvdmFyL2RiJywgMDc3NywgdHJ1ZSk7CiAgICAkZGIgPSBuZXcgUERPKCdzcWxpdGU6JyAuICRkYl9wYXRoKTsKICAgICRkYi0+ZXhlYygiQ1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgdXNlcnMgKGlkIElOVEVHRVIgUFJJTUFSWSBLRVkgQVVUT0lOQ1JFTUVOVCwgdXNlcm5hbWUgVkFSQ0hBUig2NCkgTk9UIE5VTEwsIHBhc3N3b3JkIFZBUkNIQVIoMTI4KSBOT1QgTlVMTCwgcm9sZSBWQVJDSEFSKDMyKSBOT1QgTlVMTCBERUZBVUxUICd1c2VyJykiKTsKICAgICRkYi0+ZXhlYygiQ1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgcHJvZHVjdHMgKGlkIElOVEVHRVIgUFJJTUFSWSBLRVkgQVVUT0lOQ1JFTUVOVCwgbmFtZSBWQVJDSEFSKDEyOCkgTk9UIE5VTEwsIGRlc2NyaXB0aW9uIFRFWFQpIik7CiAgICAkZGItPmV4ZWMoIklOU0VSVCBJTlRPIHVzZXJzICh1c2VybmFtZSwgcGFzc3dvcmQsIHJvbGUpIFZBTFVFUyAoJ2FkbWluJywgJ1N1cGVyU2VjcmV0MTIzJywgJ2FkbWluaXN0cmF0b3InKSwgKCdhbGljZScsICdwYXNzd29yZDEnLCAndXNlcicpLCAoJ2JvYicsICdsZXRtZWluJywgJ3VzZXInKSIpOwogICAgJGRiLT5leGVjKCJJTlNFUlQgSU5UTyBwcm9kdWN0cyAobmFtZSwgZGVzY3JpcHRpb24pIFZBTFVFUyAoJ1dpZGdldCBBJywgJ0Egc3RhbmRhcmQgd2lkZ2V0JyksICgnV2lkZ2V0IEInLCAnQW4gaW1wcm92ZWQgd2lkZ2V0JyksICgnR2FkZ2V0IFgnLCAnQSBmYW5jeSBnYWRnZXQnKSwgKCdHYWRnZXQgWScsICdBbiBhZHZhbmNlZCBnYWRnZXQnKSIpOwp9IGVsc2UgewogICAgJGRiID0gbmV3IFBETygnc3FsaXRlOicgLiAkZGJfcGF0aCk7Cn0KCiRwYWdlID0gaXNzZXQoJF9HRVRbJ3BhZ2UnXSkgPyAkX0dFVFsncGFnZSddIDogJ2hvbWUnOwokbWVzc2FnZSA9ICcnOwokdXNlcm5hbWVfb3V0ID0gJyc7CiRyb2xlX291dCA9ICcnOwokc2VhcmNoX3Jlc3VsdHMgPSBbXTsKJHNlYXJjaCA9ICcnOwoKaWYgKCRwYWdlID09PSAnbG9naW4nICYmICRfU0VSVkVSWydSRVFVRVNUX01FVEhPRCddID09PSAnUE9TVCcpIHsKICAgICR1c2VybmFtZSA9ICRfUE9TVFsndXNlcm5hbWUnXTsKICAgICRwYXNzd29yZCA9ICRfUE9TVFsncGFzc3dvcmQnXTsKICAgICRxdWVyeSA9ICJTRUxFQ1QgdXNlcm5hbWUsIHJvbGUgRlJPTSB1c2VycyBXSEVSRSB1c2VybmFtZT0nIiAuICR1c2VybmFtZSAuICInIEFORCBwYXNzd29yZD0nIiAuICRwYXNzd29yZCAuICInIjsKICAgICRyZXN1bHQgPSAkZGItPnF1ZXJ5KCRxdWVyeSk7CiAgICBpZiAoJHJlc3VsdCkgewogICAgICAgICRyb3cgPSAkcmVzdWx0LT5mZXRjaChQRE86OkZFVENIX0FTU09DKTsKICAgICAgICBpZiAoJHJvdykgewogICAgICAgICAgICAkdXNlcm5hbWVfb3V0ID0gJHJvd1sndXNlcm5hbWUnXTsKICAgICAgICAgICAgJHJvbGVfb3V0ID0gJHJvd1sncm9sZSddOwogICAgICAgICAgICAkbWVzc2FnZSA9ICdMb2dpbiBzdWNjZXNzZnVsISc7CiAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgJG1lc3NhZ2UgPSAnSW52YWxpZCBjcmVkZW50aWFscy4nOwogICAgICAgIH0KICAgIH0gZWxzZSB7CiAgICAgICAgJG1lc3NhZ2UgPSAnUXVlcnkgZXJyb3IuJzsKICAgIH0KfQoKaWYgKCRwYWdlID09PSAnc2VhcmNoJykgewogICAgJHNlYXJjaCA9IGlzc2V0KCRfR0VUWydxJ10pID8gJF9HRVRbJ3EnXSA6ICcnOwogICAgJHN0bXQgPSAkZGItPnByZXBhcmUoJ1NFTEVDVCBuYW1lLCBkZXNjcmlwdGlvbiBGUk9NIHByb2R1Y3RzIFdIRVJFIG5hbWUgTElLRSA6c2VhcmNoJyk7CiAgICAkc3RtdC0+ZXhlY3V0ZShbJzpzZWFyY2gnID0+ICclJyAuICRzZWFyY2ggLiAnJSddKTsKICAgICRzZWFyY2hfcmVzdWx0cyA9ICRzdG10LT5mZXRjaEFsbChQRE86OkZFVENIX0FTU09DKTsKfQo/Pgo8IURPQ1RZUEUgaHRtbD4KPGh0bWw+CjxoZWFkPjx0aXRsZT5Qcm9kdWN0IFN0b3JlPC90aXRsZT48L2hlYWQ+Cjxib2R5Pgo8P3BocCBpZiAoJHBhZ2UgPT09ICdob21lJyk6ID8+CjxoMT5XZWxjb21lIHRvIFByb2R1Y3QgU3RvcmU8L2gxPgo8cD48YSBocmVmPSI/cGFnZT1zZWFyY2giPlNlYXJjaCBQcm9kdWN0czwvYT4gfCA8YSBocmVmPSI/cGFnZT1sb2dpbiI+TG9naW48L2E+PC9wPgo8P3BocCBlbHNlaWYgKCRwYWdlID09PSAnc2VhcmNoJyk6ID8+CjxoMT5Qcm9kdWN0IFNlYXJjaDwvaDE+Cjxmb3JtIG1ldGhvZD0iR0VUIiBhY3Rpb249Ii9pbmRleC5waHAiPgogIDxpbnB1dCB0eXBlPSJoaWRkZW4iIG5hbWU9InBhZ2UiIHZhbHVlPSJzZWFyY2giPgogIDxpbnB1dCB0eXBlPSJ0ZXh0IiBuYW1lPSJxIiB2YWx1ZT0iPD9waHAgZWNobyBodG1sc3BlY2lhbGNoYXJzKCRzZWFyY2gpOyA/PiIgcGxhY2Vob2xkZXI9IlNlYXJjaC4uLiI+CiAgPGlucHV0IHR5cGU9InN1Ym1pdCIgdmFsdWU9IlNlYXJjaCI+CjwvZm9ybT4KPD9waHAgaWYgKCFlbXB0eSgkc2VhcmNoX3Jlc3VsdHMpKTogPz4KPHRhYmxlIGJvcmRlcj0iMSI+Cjx0cj48dGg+TmFtZTwvdGg+PHRoPkRlc2NyaXB0aW9uPC90aD48L3RyPgo8P3BocCBmb3JlYWNoICgkc2VhcmNoX3Jlc3VsdHMgYXMgJHJvdyk6ID8+Cjx0cj48dGQ+PD9waHAgZWNobyBodG1sc3BlY2lhbGNoYXJzKCRyb3dbJ25hbWUnXSk7ID8+PC90ZD48dGQ+PD9waHAgZWNobyBodG1sc3BlY2lhbGNoYXJzKCRyb3dbJ2Rlc2NyaXB0aW9uJ10pOyA/PjwvdGQ+PC90cj4KPD9waHAgZW5kZm9yZWFjaDsgPz4KPC90YWJsZT4KPD9waHAgZWxzZTogPz4KPHA+Tm8gcmVzdWx0cyBmb3VuZC48L3A+Cjw/cGhwIGVuZGlmOyA/Pgo8cD48YSBocmVmPSIvaW5kZXgucGhwIj5Ib21lPC9hPjwvcD4KPD9waHAgZWxzZWlmICgkcGFnZSA9PT0gJ2xvZ2luJyk6ID8+CjxoMT5Mb2dpbjwvaDE+Cjw/cGhwIGlmICgkbWVzc2FnZSk6ID8+CjxwPjw/cGhwIGVjaG8gJG1lc3NhZ2U7ID8+PC9wPgo8P3BocCBpZiAoJHVzZXJuYW1lX291dCk6ID8+CjxwPldlbGNvbWUsIDw/cGhwIGVjaG8gJHVzZXJuYW1lX291dDsgPz48L3A+CjxwPlJvbGU6IDw/cGhwIGVjaG8gJHJvbGVfb3V0OyA/PjwvcD4KPD9waHAgZW5kaWY7ID8+Cjw/cGhwIGVuZGlmOyA/Pgo8Zm9ybSBtZXRob2Q9IlBPU1QiIGFjdGlvbj0iL2luZGV4LnBocD9wYWdlPWxvZ2luIj4KICA8bGFiZWw+VXNlcm5hbWU6IDxpbnB1dCB0eXBlPSJ0ZXh0IiBuYW1lPSJ1c2VybmFtZSI+PC9sYWJlbD48YnI+CiAgPGxhYmVsPlBhc3N3b3JkOiA8aW5wdXQgdHlwZT0icGFzc3dvcmQiIG5hbWU9InBhc3N3b3JkIj48L2xhYmVsPjxicj4KICA8aW5wdXQgdHlwZT0ic3VibWl0IiB2YWx1ZT0iTG9naW4iPgo8L2Zvcm0+CjxwPjxhIGhyZWY9Ii9pbmRleC5waHAiPkhvbWU8L2E+PC9wPgo8P3BocCBlbmRpZjsgPz4KPC9ib2R5Pgo8L2h0bWw+Cg==' | base64 -d > /var/www/html/index.php

# Ensure www-data writable dirs
mkdir -p /var/db && chown www-data:www-data /var/db
mkdir -p /var/www/html/uploads && chown www-data:www-data /var/www/html/uploads

# Start application
cd /var/www/html
nohup service apache2 start > /var/log/webapp.log 2>&1 &
sleep 3

# Healthcheck
curl -sf http://localhost/app.php || curl -sf http://localhost/ && echo 'deploy_ok' || echo 'deploy_failed'

# --- ssh_login_with_creds ---

# Install OpenSSH server
apt-get update -y
apt-get install -y openssh-server

# Ensure SSH runtime directory exists
mkdir -p /var/run/sshd

# Configure SSH to allow password authentication
# Remove any existing directives and append clean config
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/^#\?UsePAM.*/UsePAM yes/' /etc/ssh/sshd_config
sed -i 's/^#\?ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config

# Ensure PasswordAuthentication line exists
grep -q '^PasswordAuthentication' /etc/ssh/sshd_config || echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config

# Ensure KbdInteractiveAuthentication is not blocking logins
sed -i 's/^#\?KbdInteractiveAuthentication.*/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config

# Create user 'dbuser' with bash shell (idempotent)
useradd -m -s /bin/bash dbuser 2>/dev/null || true

# Set password
echo 'dbuser:SuperSecret123' | chpasswd

# Place flag file
mkdir -p /home/dbuser
echo 'FLAG{ssh_pivot_successful_via_sqli_credentials}' > /home/dbuser/flag.txt
chown dbuser:dbuser /home/dbuser/flag.txt
chmod 644 /home/dbuser/flag.txt

# Generate SSH host keys if not present
ssh-keygen -A

# Start SSH service (try systemctl first, fall back to direct invocation)
service ssh stop 2>/dev/null || true
killall sshd 2>/dev/null || true
/usr/sbin/sshd

echo 'SSH setup complete. User dbuser created with password SuperSecret123'
