"""Step: Finalize multi-box topology output package.

Single-box: no-op — output was already written by run_finalize_script.

Multi-box: writes a self-contained output directory containing:
  - {box_id}_deploy.sh     per-box deployment scripts
  - docker-compose.yml     orchestration (runtime deployment, not build-time)
  - playbook.json          machine-readable attack chain
  - README.md              human-readable guide
"""

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, TYPE_CHECKING

import rich

from game_of_everything.models import NetworkTopology
from game_of_everything.state import GoEState
from game_of_everything.topology_utils import topological_order

if TYPE_CHECKING:
    from game_of_everything.ui import GoEConsole

# Project root: steps/ → game_of_everything/ → src/ → game_of_everything/ → (project root)
_PROJECT_ROOT = Path(__file__).parent.parent.parent.parent


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _slugify(name: str) -> str:
    """Convert a scenario name to a safe directory-name slug."""
    slug = re.sub(r"[^\w\s-]", "", name.lower())
    slug = re.sub(r"[\s_]+", "_", slug).strip("_-")
    return slug[:40]  # cap length


def _build_docker_compose(topology: NetworkTopology) -> str:
    """Generate a docker-compose.yml for runtime deployment of all boxes."""
    lines = [
        "# Auto-generated by Game of Everything",
        f"# Scenario: {topology.scenario_name}",
        "",
        "networks:",
        "  goe_net:",
        "    driver: bridge",
        "",
        "services:",
    ]

    ordered = topological_order(topology)
    for box in ordered:
        lines.append(f"  {box.box_id}:")
        lines.append(f"    image: {box.os}")
        lines.append(f"    hostname: {box.hostname}")
        lines.append("    networks:")
        lines.append("      - goe_net")

        # Expose declared services as host-mapped ports (sequential offset to avoid collisions)
        if box.services:
            idx = ordered.index(box)
            lines.append("    ports:")
            for svc in box.services:
                # e.g. "http:80" or "ssh:22"
                parts = svc.split(":")
                if len(parts) == 2:
                    try:
                        container_port = int(parts[1])
                        host_port = container_port + idx * 1000
                        lines.append(f'      - "{host_port}:{container_port}"')
                    except ValueError:
                        pass

        lines.append(f"    volumes:")
        lines.append(f"      - ./{box.box_id}_deploy.sh:/opt/deploy.sh:ro")
        lines.append(
            "    entrypoint: "
            '["bash", "-c", "chmod +x /opt/deploy.sh && /opt/deploy.sh && exec sleep infinity"]'
        )
        lines.append("")

    return "\n".join(lines)


def _build_playbook(topology: NetworkTopology, deploy_scripts: Dict[str, str]) -> dict:
    """Build the machine-readable attack chain playbook."""
    attack_chain = []

    # Step 0: entry-point exploitation (one step per entry box)
    for ep in topology.entry_point:
        entry_box = next(b for b in topology.boxes if b.box_id == ep)
        attack_chain.append({
            "step": 0,
            "box": ep,
            "hostname": entry_box.hostname,
            "action": f"Exploit entry-point box: {entry_box.role}",
            "tool": "See per-box deploy script",
        })

    # Steps 1..N: pivot steps derived from topology
    for i, pivot in enumerate(topology.pivots):
        secret = next(
            (s for s in topology.shared_secrets if s.key == pivot.secret_ref), None
        )
        target_box = next(
            (b for b in topology.boxes if b.box_id == pivot.to_box), None
        )
        step: dict = {
            "step": i + 1,
            "box": pivot.to_box,
            "hostname": target_box.hostname if target_box else pivot.to_box,
            "action": pivot.description,
            "pivot_method": pivot.method,
        }
        if secret:
            step["artifact"] = f"{secret.target_user}:{secret.value}" if secret.access_method != "ssh_key" else "SSH private key"
            step["access_method"] = secret.access_method
        attack_chain.append(step)

    return {
        "scenario_name": topology.scenario_name,
        "entry_point": topology.entry_point,
        "attack_narrative": topology.attack_narrative,
        "attack_chain": attack_chain,
        "shared_secrets": [
            {
                "key": s.key,
                "value": s.value,
                "user": s.target_user,
                "description": s.description,
                "access_method": s.access_method,
                "source_box": s.source_box,
                "target_box": s.target_box,
            }
            for s in topology.shared_secrets
        ],
        "chain_probes": [
            {
                "step": cp.step,
                "from_container": cp.from_container,
                "target_hostname": cp.target_hostname,
                "command": cp.command,
                "success_pattern": cp.success_pattern,
            }
            for cp in topology.chain_probes
        ],
    }


def _build_readme(topology: NetworkTopology, deploy_scripts: Dict[str, str], credential_warnings: List[str] = []) -> str:
    """Generate a human-readable README for the scenario."""
    lines = [
        f"# {topology.scenario_name}",
        "",
        "## Scenario Overview",
        "",
        topology.narrative,
        "",
        "## Attack Path",
        "",
        topology.attack_narrative,
        "",
        "## Network Topology",
        "",
        f"**Entry Point{'s' if len(topology.entry_point) > 1 else ''}**: {', '.join(f'`{ep}`' for ep in topology.entry_point)}",
        "",
        "| Box ID | Hostname | Role |",
        "|--------|----------|------|",
    ]
    for box in topological_order(topology):
        entry_tag = " *(entry)*" if box.box_id in topology.entry_point else ""
        lines.append(f"| `{box.box_id}` | `{box.hostname}` | {box.role}{entry_tag} |")

    if topology.pivots:
        lines += [
            "",
            "## Pivot Chain",
            "",
        ]
        for p in topology.pivots:
            lines.append(f"- **{p.from_box}** → **{p.to_box}** `[{p.method}]`: {p.description}")

    if topology.shared_secrets:
        lines += [
            "",
            "## Shared Secrets",
            "",
            "| Key | User | Value | Access Method | Source Box → Target Box |",
            "|-----|------|-------|---------------|------------------------|",
        ]
        for s in topology.shared_secrets:
            lines.append(
                f"| `{s.key}` | `{s.target_user}` | `{s.value}` "
                f"| {s.access_method} | {s.source_box} → {s.target_box} |"
            )

    lines += [
        "",
        "## Quick Start",
        "",
        "```bash",
        "docker-compose up -d",
        "```",
        "",
        "Startup takes 2–3 minutes per box (packages install at container start).",
        "",
        "## Per-Box Scripts",
        "",
    ]
    for box in topological_order(topology):
        script_size = len(deploy_scripts.get(box.box_id, ""))
        lines.append(f"- `{box.box_id}_deploy.sh` — {box.role} ({script_size} chars)")

    if topology.chain_probes:
        lines += [
            "",
            "## Chain Test Probes",
            "",
            "Run these from the attacker container to validate the attack chain:",
            "",
        ]
        for cp in topology.chain_probes:
            lines.append(f"**Step {cp.step}** (target: `{cp.target_hostname}`):")
            lines.append(f"```bash")
            lines.append(cp.command)
            lines.append("```")
            lines.append("")

    if topology.explicit_decisions:
        lines += [
            "## Synthesis Decisions",
            "",
            "The following were decided by the synthesis agent, not specified in the prompt:",
            "",
        ]
        for dec in topology.explicit_decisions:
            lines.append(f"- {dec}")

    if credential_warnings:
        lines += [
            "",
            "## \u26a0\ufe0f Credential Warnings",
            "",
            "The following shared secrets could not be verified in their deploy scripts:",
            "",
        ]
        for w in credential_warnings:
            lines.append(f"- {w}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main step
# ---------------------------------------------------------------------------

def _out(ui: Optional["GoEConsole"], msg: str) -> None:
    """Print via ui.info() if available, else rich.print()."""
    if ui:
        ui.info(msg)
    else:
        rich.print(msg)


def run_finalize_topology(
    state: GoEState,
    agents_config: dict,
    tasks_config: dict,
    ui: Optional["GoEConsole"] = None,
) -> None:
    """Write the multi-box output package.

    Single-box: no-op (run_finalize_script already wrote the deploy script).
    Multi-box: writes deploy scripts + docker-compose.yml + playbook.json + README.md
               into output/<timestamp>_<slug>/.

    Args:
        state: Flow state (read-only for this step).
        agents_config: Loaded agents.yaml dict (unused).
        tasks_config: Loaded tasks.yaml dict (unused).
        ui: Optional GoEConsole for structured output.
    """
    topology = state.topology
    if topology is None or len(topology.boxes) <= 1:
        _out(ui,
            "[dim]run_finalize_topology: single-box or no topology — "
            "output already written by finalize_script.[/dim]"
        )
        return

    deploy_scripts = state.deploy_scripts
    if not deploy_scripts:
        _out(ui, "[bold yellow]run_finalize_topology: no deploy scripts collected — skipping.[/bold yellow]")
        return

    # Build output directory
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    slug = _slugify(topology.scenario_name)
    out_dir = _PROJECT_ROOT / "output" / f"{timestamp}_{slug}"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Store output path on state for summary
    state.output_path = str(out_dir)

    _out(ui, "")
    _out(ui, "  Output:")

    # Per-box deploy scripts
    for box in topology.boxes:
        script = deploy_scripts.get(box.box_id)
        if script:
            script_path = out_dir / f"{box.box_id}_deploy.sh"
            script_path.write_text(script, encoding="utf-8")
            script_path.chmod(0o755)
            _out(ui, f"  [green]✓[/green] {script_path.name}")
        else:
            _out(ui, f"  [yellow]✗[/yellow] {box.box_id}_deploy.sh — no script")

    # docker-compose.yml
    compose_content = _build_docker_compose(topology)
    compose_path = out_dir / "docker-compose.yml"
    compose_path.write_text(compose_content, encoding="utf-8")
    _out(ui, f"  [green]✓[/green] docker-compose.yml")

    # playbook.json
    playbook = _build_playbook(topology, deploy_scripts)
    playbook_path = out_dir / "playbook.json"
    playbook_path.write_text(json.dumps(playbook, indent=2), encoding="utf-8")
    _out(ui, f"  [green]✓[/green] playbook.json")

    # README.md
    readme_content = _build_readme(topology, deploy_scripts, state.credential_warnings)
    readme_path = out_dir / "README.md"
    readme_path.write_text(readme_content, encoding="utf-8")
    _out(ui, f"  [green]✓[/green] README.md")
