#!/bin/bash
set -e
# --- sqli_login ---
export DEBIAN_FRONTEND=noninteractive

# Install runtime
apt-get update -qq
apt-get install -y apache2 php libapache2-mod-php php-mysql php-sqlite3

mkdir -p /var/www/html
# Write index.php
echo 'PD9waHAKJGRiUGF0aCA9ICcvdmFyL2RiL2FwcC5kYic7CmlmICghaXNfZGlyKCcvdmFyL2RiJykpIHsKICAgIG1rZGlyKCcvdmFyL2RiJywgMDc1NSwgdHJ1ZSk7Cn0KJGRiID0gbmV3IFBETygnc3FsaXRlOicgLiAkZGJQYXRoKTsKJGRiLT5leGVjKCdDUkVBVEUgVEFCTEUgSUYgTk9UIEVYSVNUUyBwcm9kdWN0cyAoaWQgSU5URUdFUiBQUklNQVJZIEtFWSBBVVRPSU5DUkVNRU5ULCBuYW1lIFZBUkNIQVIoMTI4KSwgZGVzY3JpcHRpb24gVkFSQ0hBUigyNTYpKScpOwokZGItPmV4ZWMoJ0NSRUFURSBUQUJMRSBJRiBOT1QgRVhJU1RTIHVzZXJzIChpZCBJTlRFR0VSIFBSSU1BUlkgS0VZIEFVVE9JTkNSRU1FTlQsIHVzZXJuYW1lIFZBUkNIQVIoNjQpLCBwYXNzd29yZCBWQVJDSEFSKDEyOCkpJyk7CiRwYyA9ICRkYi0+cXVlcnkoJ1NFTEVDVCBDT1VOVCgqKSBGUk9NIHByb2R1Y3RzJyktPmZldGNoQ29sdW1uKCk7CmlmICgkcGMgPT0gMCkgewogICAgJGRiLT5leGVjKCJJTlNFUlQgSU5UTyBwcm9kdWN0cyAobmFtZSwgZGVzY3JpcHRpb24pIFZBTFVFUyAoJ1dpZGdldCBBbHBoYScsICdBIHN0YW5kYXJkIGFsdW1pbnVtIHdpZGdldCcpLCAoJ1dpZGdldCBCZXRhJywgJ0FuIHVwZ3JhZGVkIHBvbHltZXIgd2lkZ2V0JyksICgnR2FkZ2V0IFBybycsICdQcm9mZXNzaW9uYWwgZ3JhZGUgZ2FkZ2V0JyksICgnR2FkZ2V0IExpdGUnLCAnTGlnaHR3ZWlnaHQgY29uc3VtZXIgZ2FkZ2V0JyksICgnU3VwZXJUb29sJywgJ011bHRpLXB1cnBvc2UgdG9vbCBmb3IgcHJvZmVzc2lvbmFscycpIik7Cn0KJHVjID0gJGRiLT5xdWVyeSgnU0VMRUNUIENPVU5UKCopIEZST00gdXNlcnMnKS0+ZmV0Y2hDb2x1bW4oKTsKaWYgKCR1YyA9PSAwKSB7CiAgICAkZGItPmV4ZWMoIklOU0VSVCBJTlRPIHVzZXJzICh1c2VybmFtZSwgcGFzc3dvcmQpIFZBTFVFUyAoJ2FkbWluJywgJ1MzY3VyM1BAc3N3MHJkJyksICgnd2VibWFzdGVyJywgJ3dlYm1hc3RlcjEyMycpLCAoJ2RidXNlcicsICdkYnBhc3N3b3JkOTknKSIpOwp9CiR1cmkgPSBzdHJ0b2soJF9TRVJWRVJbJ1JFUVVFU1RfVVJJJ10sICc/Jyk7CmlmICgkdXJpID09PSAnL2xvZ2luLnBocCcgfHwgJHVyaSA9PT0gJy9sb2dpbicpIHsKICAgICRlcnJvciA9ICcnOwogICAgJHN1Y2Nlc3MgPSAnJzsKICAgIGlmICgkX1NFUlZFUlsnUkVRVUVTVF9NRVRIT0QnXSA9PT0gJ1BPU1QnKSB7CiAgICAgICAgJHVzZXJuYW1lID0gaXNzZXQoJF9QT1NUWyd1c2VybmFtZSddKSA/ICRfUE9TVFsndXNlcm5hbWUnXSA6ICcnOwogICAgICAgICRwYXNzd29yZCA9IGlzc2V0KCRfUE9TVFsncGFzc3dvcmQnXSkgPyAkX1BPU1RbJ3Bhc3N3b3JkJ10gOiAnJzsKICAgICAgICAkc3RtdCA9ICRkYi0+cHJlcGFyZSgnU0VMRUNUICogRlJPTSB1c2VycyBXSEVSRSB1c2VybmFtZSA9ID8gQU5EIHBhc3N3b3JkID0gPycpOwogICAgICAgICRzdG10LT5leGVjdXRlKFskdXNlcm5hbWUsICRwYXNzd29yZF0pOwogICAgICAgICR1c2VyID0gJHN0bXQtPmZldGNoKFBETzo6RkVUQ0hfQVNTT0MpOwogICAgICAgIGlmICgkdXNlcikgewogICAgICAgICAgICAkc3VjY2VzcyA9ICdXZWxjb21lLCAnIC4gaHRtbHNwZWNpYWxjaGFycygkdXNlclsndXNlcm5hbWUnXSkgLiAnISc7CiAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgJGVycm9yID0gJ0ludmFsaWQgdXNlcm5hbWUgb3IgcGFzc3dvcmQuJzsKICAgICAgICB9CiAgICB9CiAgICBlY2hvICc8IURPQ1RZUEUgaHRtbD48aHRtbD48aGVhZD48dGl0bGU+TG9naW48L3RpdGxlPjxzdHlsZT5ib2R5e2ZvbnQtZmFtaWx5OkFyaWFsLHNhbnMtc2VyaWY7bWFyZ2luOjQwcHg7fS5sb2dpbi1ib3h7bWF4LXdpZHRoOjM1MHB4O21hcmdpbjowIGF1dG87Ym9yZGVyOjFweCBzb2xpZCAjY2NjO3BhZGRpbmc6MzBweDtib3JkZXItcmFkaXVzOjRweDt9aDJ7dGV4dC1hbGlnbjpjZW50ZXI7fWlucHV0W3R5cGU9dGV4dF0saW5wdXRbdHlwZT1wYXNzd29yZF17d2lkdGg6MTAwJTtwYWRkaW5nOjhweDttYXJnaW46NnB4IDAgMTZweCAwO2JveC1zaXppbmc6Ym9yZGVyLWJveDt9aW5wdXRbdHlwZT1zdWJtaXRde3dpZHRoOjEwMCU7cGFkZGluZzoxMHB4O2JhY2tncm91bmQ6IzRhOTBkOTtjb2xvcjp3aGl0ZTtib3JkZXI6bm9uZTtjdXJzb3I6cG9pbnRlcjtmb250LXNpemU6MTZweDt9LmVycm9ye2NvbG9yOnJlZDt9LnN1Y2Nlc3N7Y29sb3I6Z3JlZW47fWF7Y29sb3I6IzRhOTBkOTt9PC9zdHlsZT48L2hlYWQ+PGJvZHk+PGRpdiBjbGFzcz0ibG9naW4tYm94Ij48aDI+TG9naW48L2gyPjxwPjxhIGhyZWY9Ii9pbmRleC5waHAiPkJhY2sgdG8gU2VhcmNoPC9hPjwvcD4nOwogICAgaWYgKCRlcnJvcikgZWNobyAnPHAgY2xhc3M9ImVycm9yIj4nIC4gaHRtbHNwZWNpYWxjaGFycygkZXJyb3IpIC4gJzwvcD4nOwogICAgaWYgKCRzdWNjZXNzKSBlY2hvICc8cCBjbGFzcz0ic3VjY2VzcyI+JyAuICRzdWNjZXNzIC4gJzwvcD4nOwogICAgZWNobyAnPGZvcm0gbWV0aG9kPSJQT1NUIiBhY3Rpb249Ii9sb2dpbi5waHAiPjxsYWJlbD5Vc2VybmFtZTo8L2xhYmVsPjxpbnB1dCB0eXBlPSJ0ZXh0IiBuYW1lPSJ1c2VybmFtZSIgcmVxdWlyZWQ+PGxhYmVsPlBhc3N3b3JkOjwvbGFiZWw+PGlucHV0IHR5cGU9InBhc3N3b3JkIiBuYW1lPSJwYXNzd29yZCIgcmVxdWlyZWQ+PGlucHV0IHR5cGU9InN1Ym1pdCIgdmFsdWU9IkxvZ2luIj48L2Zvcm0+PC9kaXY+PC9ib2R5PjwvaHRtbD4nOwp9IGVsc2UgewogICAgZWNobyAnPCFET0NUWVBFIGh0bWw+PGh0bWw+PGhlYWQ+PHRpdGxlPlByb2R1Y3QgQ2F0YWxvZzwvdGl0bGU+PHN0eWxlPmJvZHl7Zm9udC1mYW1pbHk6QXJpYWwsc2Fucy1zZXJpZjttYXJnaW46NDBweDt9dGFibGV7Ym9yZGVyLWNvbGxhcHNlOmNvbGxhcHNlO3dpZHRoOjEwMCU7fXRoLHRke2JvcmRlcjoxcHggc29saWQgI2NjYztwYWRkaW5nOjhweCAxMnB4O3RleHQtYWxpZ246bGVmdDt9dGh7YmFja2dyb3VuZDojNGE5MGQ5O2NvbG9yOndoaXRlO310cjpudGgtY2hpbGQoZXZlbil7YmFja2dyb3VuZDojZjJmMmYyO30uc2VhcmNoLWZvcm17bWFyZ2luLWJvdHRvbToyMHB4O31pbnB1dFt0eXBlPXRleHRde3BhZGRpbmc6NnB4O3dpZHRoOjMwMHB4O31pbnB1dFt0eXBlPXN1Ym1pdF17cGFkZGluZzo2cHggMTZweDtiYWNrZ3JvdW5kOiM0YTkwZDk7Y29sb3I6d2hpdGU7Ym9yZGVyOm5vbmU7Y3Vyc29yOnBvaW50ZXI7fWF7Y29sb3I6IzRhOTBkOTt9PC9zdHlsZT48L2hlYWQ+PGJvZHk+PGgxPlByb2R1Y3QgQ2F0YWxvZzwvaDE+PHA+PGEgaHJlZj0iL2xvZ2luLnBocCI+TG9naW48L2E+PC9wPjxkaXYgY2xhc3M9InNlYXJjaC1mb3JtIj48Zm9ybSBtZXRob2Q9IkdFVCIgYWN0aW9uPSIvaW5kZXgucGhwIj48bGFiZWwgZm9yPSJzZWFyY2giPlNlYXJjaCBQcm9kdWN0czo8L2xhYmVsPjxicj48YnI+PGlucHV0IHR5cGU9InRleHQiIGlkPSJzZWFyY2giIG5hbWU9InNlYXJjaCIgcGxhY2Vob2xkZXI9IkVudGVyIHByb2R1Y3QgbmFtZS4uLiIgdmFsdWU9IicgLiAoaXNzZXQoJF9HRVRbJ3NlYXJjaCddKSA/IGh0bWxzcGVjaWFsY2hhcnMoJF9HRVRbJ3NlYXJjaCddLCBFTlRfUVVPVEVTKSA6ICcnKSAuICciPjxpbnB1dCB0eXBlPSJzdWJtaXQiIHZhbHVlPSJTZWFyY2giPjwvZm9ybT48L2Rpdj4nOwogICAgaWYgKGlzc2V0KCRfR0VUWydzZWFyY2gnXSkpIHsKICAgICAgICAkc2VhcmNoID0gJF9HRVRbJ3NlYXJjaCddOwogICAgICAgICRxdWVyeSA9ICJTRUxFQ1QgbmFtZSwgZGVzY3JpcHRpb24gRlJPTSBwcm9kdWN0cyBXSEVSRSBuYW1lIExJS0UgJyUiIC4gJHNlYXJjaCAuICIlJyI7CiAgICAgICAgJHJlc3VsdCA9ICRkYi0+cXVlcnkoJHF1ZXJ5KTsKICAgICAgICBpZiAoJHJlc3VsdCA9PT0gZmFsc2UpIHsKICAgICAgICAgICAgJGluZm8gPSAkZGItPmVycm9ySW5mbygpOwogICAgICAgICAgICBlY2hvICc8cCBzdHlsZT0iY29sb3I6cmVkOyI+UXVlcnkgZXJyb3I6ICcgLiBodG1sc3BlY2lhbGNoYXJzKCRpbmZvWzJdKSAuICc8L3A+JzsKICAgICAgICB9IGVsc2UgewogICAgICAgICAgICAkcm93cyA9ICRyZXN1bHQtPmZldGNoQWxsKFBETzo6RkVUQ0hfQVNTT0MpOwogICAgICAgICAgICBpZiAoY291bnQoJHJvd3MpID09PSAwKSB7CiAgICAgICAgICAgICAgICBlY2hvICc8cD5ObyBwcm9kdWN0cyBmb3VuZC48L3A+JzsKICAgICAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgICAgIGVjaG8gJzx0YWJsZT48dHI+PHRoPk5hbWU8L3RoPjx0aD5EZXNjcmlwdGlvbjwvdGg+PC90cj4nOwogICAgICAgICAgICAgICAgZm9yZWFjaCAoJHJvd3MgYXMgJHJvdykgewogICAgICAgICAgICAgICAgICAgIGVjaG8gJzx0cj48dGQ+JyAuICRyb3dbJ25hbWUnXSAuICc8L3RkPjx0ZD4nIC4gJHJvd1snZGVzY3JpcHRpb24nXSAuICc8L3RkPjwvdHI+JzsKICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIGVjaG8gJzwvdGFibGU+JzsKICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0gZWxzZSB7CiAgICAgICAgZWNobyAnPHA+RW50ZXIgYSBzZWFyY2ggdGVybSBhYm92ZSB0byBmaW5kIHByb2R1Y3RzLjwvcD4nOwogICAgfQogICAgZWNobyAnPC9ib2R5PjwvaHRtbD4nOwp9Cj8+' | base64 -d > /var/www/html/index.php

# Ensure www-data writable dirs
mkdir -p /var/db && chown www-data:www-data /var/db
mkdir -p /var/www/html/uploads && chown www-data:www-data /var/www/html/uploads

# Start application
cd /var/www/html
nohup service apache2 start > /var/log/webapp.log 2>&1 &
sleep 3

# Healthcheck
curl -sf http://localhost/app.php || curl -sf http://localhost/ && echo 'deploy_ok' || echo 'deploy_failed'

# --- ssh_access ---

# Update package lists
apt-get update -y

# Install OpenSSH server and sshpass
apt-get install -y openssh-server sshpass

# Create the admin user with a bash shell and home directory (idempotent)
id -u admin > /dev/null 2>&1 || useradd -m -s /bin/bash admin

# Set the password for admin
echo 'admin:S3cur3P@ssw0rd' | chpasswd

# Configure SSH to allow password authentication
# Remove any existing PasswordAuthentication lines and add a clean one
sed -i '/^PasswordAuthentication/d' /etc/ssh/sshd_config
sed -i '/^#PasswordAuthentication/d' /etc/ssh/sshd_config
echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config

# Set PermitRootLogin to no
sed -i '/^PermitRootLogin/d' /etc/ssh/sshd_config
sed -i '/^#PermitRootLogin/d' /etc/ssh/sshd_config
echo 'PermitRootLogin no' >> /etc/ssh/sshd_config

# Ensure UsePAM is yes for password auth
sed -i '/^UsePAM/d' /etc/ssh/sshd_config
sed -i '/^#UsePAM/d' /etc/ssh/sshd_config
echo 'UsePAM yes' >> /etc/ssh/sshd_config

# Create privilege separation directory if it doesn't exist
mkdir -p /run/sshd
chmod 755 /run/sshd

# Generate host keys if they don't exist
ssh-keygen -A

# Start SSH service
service ssh start || /usr/sbin/sshd -D &

echo 'SSH setup complete. admin user created with password authentication enabled.'
