"""ServiceRegistry — loads service recipes and generates deployment scripts.

Service recipes are YAML files in recipes/ with fields:
- id, description, apt_packages, install, configure, start, healthcheck, stop, ports
- restart_after_snapshot: bool (must restart after docker commit)
- config_vars: dict of configurable parameters with apply scripts

The registry generates deterministic bash scripts with readiness gates.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import yaml

if TYPE_CHECKING:
    from goe.models.system import ServiceSpec

_RECIPES_DIR = Path(__file__).parent / "recipes"


class ServiceRegistry:
    """Loads service recipes and generates deployment/restart scripts."""

    _ALIASES: dict[str, str] = {
        "ssh": "openssh",
        "sshd": "openssh",
        "smb": "samba",
        "cifs": "samba",
        "mariadb": "mysql",
        "httpd": "apache",
        "vsftpd": "ftp",
        "php-fpm": "php_fpm",
        "memcache": "memcached",
    }

    def __init__(self):
        self._recipes: dict[str, dict] = {}
        for path in _RECIPES_DIR.glob("*.yaml"):
            data = yaml.safe_load(path.read_text())
            self._recipes[data["id"]] = data

    def _resolve_id(self, service_id: str) -> str:
        return self._ALIASES.get(service_id, service_id)

    def has_recipe(self, service_id: str) -> bool:
        """True if a recipe exists for this service id (or alias).

        Lets callers skip pseudo-services like ``web``/``database`` that are handled by the
        web runtime layer rather than the ServiceRegistry.
        """
        return self._resolve_id(service_id) in self._recipes

    def get_recipe(self, service_id: str) -> dict:
        """Get a recipe by ID (or alias). Raises ValueError if not found."""
        resolved = self._resolve_id(service_id)
        if resolved not in self._recipes:
            available = list(self._recipes.keys())
            raise ValueError(
                f"Unknown service: {service_id!r}. Available: {available}"
            )
        return self._recipes[resolved]

    def deploy_all(self, specs: list[ServiceSpec]) -> str:
        """Generate a bash script that installs, configures, and starts all services.

        Args:
            specs: List of ServiceSpec objects with id and optional config overrides

        Returns:
            Bash script with service deployment in dependency-safe order
        """
        if not specs:
            return ""

        lines = [
            "#!/bin/bash",
            "# Service deployment script (generated by ServiceRegistry)",
            "# Services are started with readiness gates and explicit error handling",
            "",
        ]

        # Deploy each service in sequence
        for spec in specs:
            recipe = self.get_recipe(spec.id)
            lines.append(f"# ===== Service: {spec.id} =====")
            lines.append(f"# {recipe['description']}")
            lines.append("")

            # Install
            install_script = recipe.get("install", "").strip()
            if install_script:
                lines.append("# Install")
                lines.append(install_script)
                lines.append("")

            # Configure
            configure_script = recipe.get("configure", "").strip()
            if configure_script:
                lines.append("# Configure")
                lines.append(configure_script)
                lines.append("")

            # Apply config_vars. Vars with after_start=false (the default) edit
            # config files that the start block reads, so they run before start.
            # Vars with after_start=true (e.g. mysql root_password, which issues
            # `mysql -e ...` against the live server) run after the readiness gate.
            config_vars = recipe.get("config_vars", {})
            self._emit_config_vars(lines, spec, config_vars, after_start=False)

            # Start (includes readiness gate)
            start_script = recipe.get("start", "").strip()
            if start_script:
                lines.append("# Start")
                lines.append(start_script)
                lines.append("")

            self._emit_config_vars(lines, spec, config_vars, after_start=True)

        lines.append("echo 'All services deployed successfully'")
        return "\n".join(lines) + "\n"

    @staticmethod
    def _emit_config_vars(
        lines: list[str],
        spec: ServiceSpec,
        config_vars: dict,
        *,
        after_start: bool,
    ) -> None:
        """Append apply scripts for the config_vars whose timing matches after_start."""
        for var_name, var_def in config_vars.items():
            if var_name not in spec.config:
                continue
            if bool(var_def.get("after_start", False)) != after_start:
                continue
            value = spec.config[var_name]
            apply_script = var_def["apply"].replace("{value}", value)
            lines.append(f"# Apply config: {var_name}")
            lines.append(apply_script)
            lines.append("")

    def restart_all(self, specs: list[ServiceSpec]) -> str:
        """Generate a script to restart services after snapshot restore.

        Only restarts services with restart_after_snapshot=true (those that
        don't survive docker commit + container recreate).

        Args:
            specs: List of ServiceSpec objects

        Returns:
            Bash script to restart services
        """
        if not specs:
            return ""

        lines = [
            "#!/bin/bash",
            "# Service restart script (after snapshot restore)",
            "",
        ]

        needs_restart = []
        for spec in specs:
            recipe = self.get_recipe(spec.id)
            if recipe.get("restart_after_snapshot", False):
                needs_restart.append((spec, recipe))

        if not needs_restart:
            lines.append("# No services require restart")
            return "\n".join(lines) + "\n"

        for spec, recipe in needs_restart:
            lines.append(f"# ===== Restart: {spec.id} =====")
            start_script = recipe.get("start", "").strip()
            if start_script:
                lines.append(start_script)
                lines.append("")

        lines.append("echo 'All services restarted successfully'")
        return "\n".join(lines) + "\n"

    def available_services(self) -> list[str]:
        """Return list of available service IDs."""
        return sorted(self._recipes.keys())


# Module-level singleton
_registry: ServiceRegistry | None = None


def get_registry() -> ServiceRegistry:
    """Get the global ServiceRegistry singleton."""
    global _registry
    if _registry is None:
        _registry = ServiceRegistry()
    return _registry
